### ISSUE TITLE
make columns/schemas the map they deserve to be

### ISSUE THREAD

**Issue by hredestig** [ProteinGym/proteingym-base#26]
I don't follow that - columns and schemas are linked. Now by index and convention (fragile). If that's the case, why not make it explicit, and if not required, allow to none - like
```toml
[records.columns.feature1]
type = "string"
[records.columns.feature2]
# no schema here
[records.columns.feature3]
type = "float"
```
Then also a little utility to turn "float" to `pl.Float32`, and avoid the `eval` which is exposing people to injection attacks 😨

_Originally posted by @hredestig in https://github.com/ProteinGym2/pg2-dataset/pull/18#discussion_r2088409440_

Suggestion: Drop schemas, polars to the rescue
